services:
  - type: web
    name: mongodb-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: <your-telegram-bot-token>
      - key: MONGO_URI
        value: <your-mongodb-uri>
